
// export const TOGGLE_EXTRA_NAV_OPTIONS = 'TOGGLE_EXTRA_NAV_OPTIONS'

export const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_SOCKET = "SET_SOCKET"